In [3]:
import pandas as pd
import numpy as np
s = pd.Series([1,3,6,np.nan,44,1])  # np.nan -->non
print(s)
dates = pd.date_range('20160101',periods=6)
print(dates)
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=['a','b','c','d'])       # 6 rows 4 columns
print(df)
print("------------------------------------------------")
df = pd.DataFrame(np.arange(12).reshape((3,4)))
print(df)  # add omdex 0,1,2,3 and 0,1,2 automatically

print("----dataframe from dict-------------------------")
df2 = pd.DataFrame({'A':1., 'B': pd.Timestamp('20130101'), 
                    'C': pd.Series(1,index=list(range(4)),dtype='float32'),
                    'D':np.array([3]*4,dtype='int32'),
                    'E': pd.Categorical(["test", "train","test","train"]),
                    'F': 'foo'})
print(df2)
print(df2.dtypes)
print("--------------index, column---------------")
print(df2.index)
print(df2.columns)
print(df2.values)
print("--------------describe ------------------")
print(df2.describe())   
print("--------------tranpot--------------------")
print(df2.T)
print("--------------sort-----------------------")
print(df2.sort_index(axis=1,ascending=False))   # sort by column
print("--------------sort by row----------------")
print(df2.sort_index(axis=0,ascending=False))

print("--------------sort by value--------------")
print(df2.sort_values(by='E'))

0     1.0
1     3.0
2     6.0
3     NaN
4    44.0
5     1.0
dtype: float64
DatetimeIndex(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
               '2016-01-05', '2016-01-06'],
              dtype='datetime64[ns]', freq='D')
                   a         b         c         d
2016-01-01 -0.547377 -1.041379  1.233774 -0.593130
2016-01-02 -0.539570  0.063478 -1.507823 -0.957669
2016-01-03  0.440422 -0.524890 -0.625927  0.042910
2016-01-04  0.678767  0.483310  0.435574  0.830956
2016-01-05 -1.347920  0.511621 -1.784942 -1.057020
2016-01-06 -0.154020  0.530956 -0.586869 -0.678014
------------------------------------------------
   0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11
----dataframe from dict-------------------------
     A          B    C  D      E    F
0  1.0 2013-01-01  1.0  3   test  foo
1  1.0 2013-01-01  1.0  3  train  foo
2  1.0 2013-01-01  1.0  3   test  foo
3  1.0 2013-01-01  1.0  3  train  foo
A           float64
B    datetime64[ns]
C           f

In [35]:
import numpy as np
import pandas as pd
my_array = np.ones(3, dtype=([('foo', int), ('bar', float)]))
print (my_array)
print ((my_array['foo']))

[(1, 1.0) (1, 1.0) (1, 1.0)]
[1 1 1]


In [18]:
data = np.array([['','Col1','Col2'],
                ['Row1',1,2],
                ['Row2',3,4]])
                
print(pd.DataFrame(data=data[1:,1:],
                  index=data[1:,0],
                  columns=data[0,1:]))

     Col1 Col2
Row1    1    2
Row2    3    4


In [11]:
my_df = pd.DataFrame(data=[4,5,6,7], index=range(0,4), columns=['A'])
print (my_df)
my_series = pd.Series({"Belgium":"Brussels", "India":"New Delhi", "United Kingdom":"London", "United States":"Washington"})
print (my_series)

   A
0  4
1  5
2  6
3  7


In [19]:
df = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6]]))
print (df)
print (df.shape) 
print (len(df))
print (list(df.columns.values))
print (df[0].count())

   0  1  2
0  1  2  3
1  4  5  6
(2, 3)
2
[0, 1, 2]
2


In [33]:
data = np.arange(9).reshape(3,3)
data +=1
print (a)
df = pd.DataFrame(data=a, index=range(0,3), columns=['A','B','C'])
print (df)
print(df.iloc[0][0])
print(df.loc[0]['A'])
print(df.at[0,'A'])
print(df.iat[0,0])
print(df.get_value(0, 'A'))
# Use `iloc[]` to select row `0`
print(df.iloc[0])

# Use `loc[]` to select column `'A'`
print(df.loc[:,'A'])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
1
1
1
1
1
A    1
B    2
C    3
Name: 0, dtype: int32
0    1
1    4
2    7
Name: A, dtype: int32


In [ ]:
df = pd.DataFrame(data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), index= [2, 'A', 4], columns=[48, 49, 50])
print (df)
# Pass `2` to `loc`
print(df.loc[2])

# Pass `2` to `iloc`# cl, ilock is the index number(0,1,2?) not index value
print(df.iloc[2])

# Pass `2` to `ix`
print(df.ix[2])

In [41]:
df = pd.DataFrame(data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), index= [2.5, 12.6, 4.8], columns=[48, 49, 50])

# There's no index labeled `2`, so you will change the index at position `2`
df.ix[2] = [60, 50, 40]
print(df)

# This will make an index labeled `2` and add the new values
df.loc[2] = [11, 12, 13]
print(df)

      48  49  50
2.5    1   2   3
12.6   4   5   6
4.8   60  50  40
      48  49  50
2.5    1   2   3
12.6   4   5   6
4.8   11  12  13


In [42]:
df = pd.DataFrame(data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=['A', 'B', 'C'])

# Use `.index`
df['D'] = df.index

# Print `df`
print(df)

   A  B  C  D
0  1  2  3  0
1  4  5  6  1
2  7  8  9  2


In [62]:
df = pd.DataFrame(data=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), columns=['A', 'B', 'C'])
# Study the DataFrame `df`
print(df)

# Append a column to `df`
df.loc[:, 2] = pd.Series(['9', '9', '9'], index=df.index)
print (df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
   A  B  C
0  1  2  9
1  4  5  9
2  7  8  9


In [63]:
# Check out the weird index of your dataframe
print(df)

# Use `reset_index()` to reset the values. 
df.reset_index(level=0, drop=True)
print (df)

   A  B  C
0  1  2  9
1  4  5  9
2  7  8  9
   A  B  C
0  1  2  9
1  4  5  9
2  7  8  9
